### ISSUE TITLE
cmd+enter should execute cell but not proceed to next cell

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/retrolab#329] opened 2022-01-26 16:48 UTC
### Problem

When I'm working on a cell, I want to execute it but not immediately move to the next cell - this helps me iterate on the current cell.

shift+enter executes the cell, but moves to the next cell. In classic notebook, cmd+enter executes the cell and doesn't move to the next cell.

### Proposed Solution

Implement cmd+enter to execute current cell and not move to next cell.

### Additional context

Brought up by @papajohn while teaching data8 at Berkeley, where we're trying to switch from classic notebook to retrolab

**Comment by jtpio** [comment] 2022-01-26 17:30
Thanks @yuvipanda for opening this issue :+1: 

I just tried with RetroLab 0.3.16 on Binder with this gist: https://gist.github.com/jtpio/4a6a34da66b32249e28df718ec30e4d7

And it seems to be working as intended on Firefox 96 (Ubuntu 20.04) with the `Ctrl-Enter` keyboard shortcut:

https://user-images.githubusercontent.com/591645/151215291-4038eefb-5987-4a5a-a622-a3e67004fbe4.mp4

**Comment by papajohn** [comment] 2022-01-26 17:36
I encountered this issue on a Mac. In old Jupyter, both Ctrl+return and Cmd+return had this behavior. I see that Ctrl+return still works in retro, which is sufficient. Thanks for the tip. Fine with me if we close this issue.

**Comment by yuvipanda** [comment] 2022-01-26 17:39
@jtpio ah, indeed - ctrl+return works, but cmd+return doesn't (as @papajohn said). Let's bind to cmd+return too?

**Comment by jtpio** [comment] 2022-01-26 18:39
I opened https://github.com/jupyterlab/retrolab/pull/330 as an attempt to fix this.

@yuvipanda @papajohn would you be able to try it on the Binder for that PR, since you both have access to a Mac? Thanks!

https://mybinder.org/v2/gh/jtpio/retrolab/cmd-enter?urlpath=retro

**Comment by yuvipanda** [comment] 2022-01-26 18:43
@jtpio it works!

**Comment by jtpio** [comment] 2022-01-26 19:30
I opened this PR upstream so it's also the case in JupyterLab by default: https://github.com/jupyterlab/jupyterlab/pull/11942

**Closed** 2022-01-26 19:46 UTC
Labels: enhancement, status:Needs Triage
